meta_product_name: "BeerWizard"
meta_title: "Beer Wizard - The place to discover Quebec Microbrews and connect with beer enthusiasts"
meta_description: "BeerWizard connects beer enthusiasts and Microbreweries in Quebec! "
meta_image: "BeerWizardbanner.png" # should exist in `app/assets/images/`
